Repository skadogg/personal-tv-guide, pull requests merged in 2023-12, with the labels that each got.

#6 Skadogg/issue3
  modules/genre.py
  modules/ld_json.py
  scrape-json-ld.py
  scrape_movies.py
  scrape_tv.py
Labels: enhancement

#23 Fixes #21 - Implement new autologin for scraping
  .gitignore
  README.md
  modules/auto_sign_in.py
  scrape_movies.py
  scrape_tv.py
Labels: documentation, enhancement

#30 Issue #26 - Extract variables to env file
  .env-sample
  .gitignore
  build_html.py
  modules/genre.py
  scrape_movies.py
  scrape_tv.py
Labels: enhancement, help wanted

#32 Merge branch 'main' into skadogg/issue25-henry-sugar
  scrape_movies.py
  scrape_tv.py
Labels: bug

#36 Skadogg/issue34-dev_mode-always-true
  scrape_movies.py
  scrape_tv.py
Labels: bug
