Repository skadogg/personal-tv-guide, pull requests merged in 2024-01, with the labels that each got.

#42 ⚡ Block image loading when using selenium
  scrape_movies.py
  scrape_tv.py
Labels: enhancement

#44 📝 Adds explanation of .env with nice, little table in readme file
  README.md
Labels: documentation

#45 ♿ Create stylesheet for visual impairment
  css/disability-pride-flag.css
Labels: enhancement

#53 Occasional errors when scraping pages with Selenium
  .gitignore
  scrape_movies.py
Labels: bug, help wanted

#54 Add project logo
  README.md
  images/Tv-Guide-Created-by-Pedrovisc-from-Noun-Project-cropped-200px.png
  images/personal_tv_guide.png
Labels: enhancement, help wanted

#59 📝 Updates readme with instructions for installing required modules
  README.md
Labels: enhancement

#57 stylesheet name a variable in .env, Added requirements.txt
  build_html.py
  modules/html.py
  requirements.txt
  sample_files/.env_sample
Labels: bug, enhancement

#60 Skadogg/issue41-movie-of-the-week
  build_html.py
  modules/html.py
  modules/justwatch.py
Labels: enhancement

#62 ✨ Movies-sorted-by-runtime
  build_html.py
  modules/html.py
  modules/justwatch.py
Labels: enhancement

#63 🚸 Balance movie and TV runtime in final output
  build_html.py
  modules/html.py
  modules/justwatch.py
Labels: enhancement

#64 Alphabetize genres for enhanced table navigation ✨
  build_html.py
Labels: enhancement

#69 🐛 Rows printing past the end time
  modules/html.py
Labels: bug

#86 🚑 Waits a few seconds before clicking
  modules/auto_sign_in.py
Labels: bug
